In [ ]:
# use tf dataset api to load dataset 
# prior to this , use downloadv3.sh and post_download.sh


# self notes
# custom function must strictly pass numpy dtype as input and numpy dtype as output ( not tensors)

In [24]:
import tensorflow  as tf
import numpy as np

In [25]:
import sys

sys.path.insert(0, '/media/saurabh/New Volume/tf_audio_sentiment/pyAudioAnalysis')

from  pyAudioAnalysis  import audioBasicIO
from  pyAudioAnalysis import audioFeatureExtraction

In [26]:
timesteps=2000 # max timesteps
data_base_directory='/media/saurabh/New Volume/tf_audio_sentiment/data_test/datav2/'

In [27]:
def audio_to_features(fileurl):
    
    [Fs, x] = audioBasicIO.readAudioFile(fileurl);
    F = audioFeatureExtraction.stFeatureExtraction(x, Fs, 0.050*Fs, 0.025*Fs);
    
    a=F[:21,:]
    b=F[33]

    b=np.expand_dims(b, axis=0)

    #print(b.shape)


    d = np.concatenate( (a, b), axis=0)
    #print(d.shape)
    d = np.swapaxes(d, 0, 1)
    return d

In [28]:
# define a function, that pads audio so that audio frames = max frames

def pad(input):
   # print(input.shape[0])
     if input.shape[0] < timesteps:
        
        diff = timesteps - input.shape[0]
        
        # pad and return input
        return np.pad(input,((0,diff),(0,0)), mode="constant")
    
     elif input.shape[0] > timesteps:
        
        return input[:timesteps,:]

In [72]:
def process_function(input):
  
  

  path=data_base_directory + str(input,'utf-8')
  print(str(input,'utf-8'))

  if 'A' in str(input,'utf-8'):
        y=0
  elif 'B'  in str(input,'utf-8'):
        y=1

  input=pad(audio_to_features(path))

  
    
  return  input,y

In [83]:
logfilepath='/media/saurabh/New Volume/tf_audio_sentiment/data_test/dataset.txt'
dataset = tf.contrib.data.TextLineDataset(logfilepath).shuffle(buffer_size=1000) #.map(map_function)

dataset = dataset.map(
    lambda filename: tuple(tf.py_func(
        process_function, [filename],  [tf.double,tf.int64])))

dataset=dataset.batch(3)


In [84]:
iterator = dataset.make_one_shot_iterator()
next_element = iterator.get_next()

In [85]:
with tf.Session() as sess:
    for i in range(1000):
      value = sess.run(next_element)
      print(value)

21_22_48039A.wav
21_10_48260B.wav
21_15_40067B.wav
(array([[[  1.32665832e-01,   3.70356099e-02,   3.26535317e+00, ...,
          -2.20095408e-01,  -2.29329164e-01,   9.53805611e-03],
        [  1.13892365e-01,   3.90662694e-02,   3.29976678e+00, ...,
          -5.65012295e-01,  -1.11482234e-01,   9.38422417e-03],
        [  1.18898623e-01,   3.43644895e-02,   3.25411840e+00, ...,
          -3.57568802e-01,  -3.54392507e-02,   9.18953922e-03],
        ..., 
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
           0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
           0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
           0.00000000e+00,   0.00000000e+00,   0.00000000e+00]],

       [[  1.41426783e-01,   1.89407474e-03,   3.11434614e+00, ...,
           4.35193237e-01,   5.87577389e-02,   1.74735722e-02],
        

21_15_40374B.wav
21_10_48320B.wav
(array([[[  3.75469337e-02,   8.25707116e-04,   1.85807384e+00, ...,
          -1.94118874e-01,  -1.42048753e-01,   2.05175194e-02],
        [  5.25657071e-02,   2.74738674e-05,   2.26146470e+00, ...,
          -2.91493166e-02,  -1.80865966e-01,   2.18773853e-02],
        [  7.13391740e-02,   6.98608457e-06,   3.06483977e+00, ...,
           1.94149127e-02,   1.08654588e-01,   1.84140025e-02],
        ..., 
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
           0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
           0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
           0.00000000e+00,   0.00000000e+00,   0.00000000e+00]],

       [[  1.05131414e-01,   3.87176147e-02,   3.13905003e+00, ...,
          -3.42304267e-01,  -3.41676378e-01,   2.16840787e-02],
        [  1.20150188e-01

21_22_16038A.wav
(array([[[  1.63954944e-01,   1.24306325e-02,   3.22028312e+00, ...,
          -1.67969302e-01,  -2.83816622e-01,   2.90206278e-03],
        [  1.75219024e-01,   1.35156630e-02,   3.20632828e+00, ...,
          -1.85911054e-01,  -2.35912523e-01,   5.47559256e-03],
        [  1.53942428e-01,   1.47312828e-02,   3.25810468e+00, ...,
          -1.48954247e-01,  -1.31139847e-01,   1.09298496e-02],
        ..., 
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
           0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
           0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
           0.00000000e+00,   0.00000000e+00,   0.00000000e+00]],

       [[  9.51188986e-02,   7.09077506e-02,   3.25487017e+00, ...,
          -1.32176159e-01,   3.60906308e-01,   3.94635062e-02],
        [  9.26157697e-02,   8.19071661e-0

KeyboardInterrupt: 