In [14]:
# use tf dataset api to load dataset 
# prior to this , use downloadv3.sh and post_download.sh


# self notes
# custom function must strictly pass numpy dtype as input and numpy dtype as output ( not tensors)

In [15]:
import tensorflow  as tf
import numpy as np

In [3]:
import sys

sys.path.insert(0, '/media/saurabh/New Volume/tf_audio_sentiment/pyAudioAnalysis')

from  pyAudioAnalysis  import audioBasicIO
from  pyAudioAnalysis import audioFeatureExtraction

In [4]:
timesteps=1000 # max timesteps
data_base_directory='/media/saurabh/New Volume/tf_audio_sentiment/data_test/datav2/'

In [5]:
def audio_to_features(fileurl):
    
    [Fs, x] = audioBasicIO.readAudioFile(fileurl);
    F = audioFeatureExtraction.stFeatureExtraction(x, Fs, 0.050*Fs, 0.025*Fs);
    
    a=F[:21,:]
    b=F[33]

    b=np.expand_dims(b, axis=0)

    #print(b.shape)


    d = np.concatenate( (a, b), axis=0)
    #print(d.shape)
    d = np.swapaxes(d, 0, 1)
    return d

In [6]:
# define a function, that pads audio so that audio frames = max frames

def pad(input):
   # print(input.shape[0])
     if input.shape[0] < timesteps:
        
        diff = timesteps - input.shape[0]
        
        # pad and return input
        return np.pad(input,((0,diff),(0,0)), mode="constant")
    
     elif input.shape[0] > timesteps:
        
        return input[:timesteps,:]

In [7]:
def process_function(input):
  
  

  path=data_base_directory + str(input,'utf-8')
  print(str(input,'utf-8'))

  if 'A' in str(input,'utf-8'):
        y=0
  elif 'B'  in str(input,'utf-8'):
        y=1

  input=pad(audio_to_features(path))

  
    
  return  input,y

In [8]:
logfilepath='/media/saurabh/New Volume/tf_audio_sentiment/data_test/dataset.txt'
dataset = tf.contrib.data.TextLineDataset(logfilepath).shuffle(buffer_size=1000) #.map(map_function)

dataset = dataset.map(
    lambda filename: tuple(tf.py_func(
        process_function, [filename],  [tf.double,tf.int64])))

dataset=dataset.batch(3)


In [9]:
iterator = dataset.make_initializable_iterator()
next_element = iterator.get_next()

In [13]:
#with tf.Session() as sess:
 #   sess.run(iterator.initializer)
  #  for i in range(1000):
   #   value = sess.run(next_element[1])
    #  print(value)

21_22_48060A.wav
21_15_40351B.wav
21_10_48063B.wav
[0 1 1]
21_15_40222B.wav
21_23_56066A.wav
21_15_40150B.wav
[1 0 1]
21_15_40203B.wav
21_10_48008B.wav
21_15_40096B.wav
[1 1 1]
21_23_56022A.wav
21_21_44013A.wav
21_24_34042A.wav
[0 0 0]
21_15_40156B.wav
21_10_48026B.wav
21_15_40343B.wav
[1 1 1]
21_15_40133B.wav
21_24_34040A.wav
21_15_40186B.wav
[1 0 1]
21_10_48166B.wav
21_15_40394B.wav
21_22_48025A.wav
[1 1 0]
21_22_48057A.wav
21_15_40377B.wav
21_15_40341B.wav
[0 1 1]
21_10_48221B.wav
21_10_48319B.wav
21_24_34074A.wav
[1 1 0]
21_24_34011A.wav
21_10_48255B.wav
21_10_48067B.wav
[0 1 1]
21_10_48119B.wav
21_10_48117B.wav
21_15_40309B.wav
[1 1 1]
21_15_40243B.wav
21_10_48179B.wav
21_22_16019A.wav
[1 1 0]
21_10_48297B.wav
21_15_40065B.wav
21_15_40250B.wav
[1 1 1]
21_10_48288B.wav
21_15_40347B.wav
21_10_48150B.wav
[1 1 1]
21_10_48014B.wav
21_10_48111B.wav
21_15_40305B.wav
[1 1 1]
21_10_48122B.wav
21_15_40358B.wav
21_24_34063A.wav
[1 1 0]
21_22_48000A.wav
21_15_40400B.wav
21_15_40217B.wav
[0 1 

KeyboardInterrupt: 