In [1]:
# use tf dataset api to load dataset 
# prior to this , use downloadv3.sh and post_download.sh


# self notes
# custom function must strictly pass numpy dtype as input and numpy dtype as output ( not tensors)

In [2]:
import tensorflow  as tf
import numpy as np

In [3]:
import sys

sys.path.insert(0, '/media/saurabh/New Volume/tf_audio_sentiment/pyAudioAnalysis')

from  pyAudioAnalysis  import audioBasicIO
from  pyAudioAnalysis import audioFeatureExtraction

In [45]:
timesteps=125 # max timesteps
data_base_directory='/media/saurabh/New Volume/tf_audio_sentiment/data_test/datav2/'

In [46]:
def audio_to_features(fileurl):
    
    [Fs, x] = audioBasicIO.readAudioFile(fileurl);
    F = audioFeatureExtraction.stFeatureExtraction(x, Fs, 0.050*Fs, 0.025*Fs);
    
    a=F[:21,:]
    b=F[33]

    b=np.expand_dims(b, axis=0)

    #print(b.shape)


    d = np.concatenate( (a, b), axis=0)
    #print(d.shape)
    d = np.swapaxes(d, 0, 1)
    return d

In [47]:
# define a function, that pads audio so that audio frames = max frames

def pad(input):
   # print(input.shape[0])
     if input.shape[0] < timesteps:
        
        diff = timesteps - input.shape[0]
        
        # pad and return input
        return np.pad(input,((0,diff),(0,0)), mode="constant")
    
     elif input.shape[0] > timesteps:
        
        return input[:timesteps,:]

In [48]:
def normalized(a, axis=-1, order=2):
    l2 = np.atleast_1d(np.linalg.norm(a, order, axis))
    l2[l2==0] = 1
    return a / np.expand_dims(l2, axis)

In [49]:
def process_function(input):
  
  

  path=data_base_directory + str(input,'utf-8')
  print(str(input,'utf-8'))

  if 'A' in str(input,'utf-8'):
        y=0
  elif 'B'  in str(input,'utf-8'):
        y=1

  input=normalized(pad(audio_to_features(path)) , axis=1 )

  
    
  return  input,y

In [50]:
logfilepath='/media/saurabh/New Volume/tf_audio_sentiment/data_test/dataset.txt'
dataset = tf.contrib.data.TextLineDataset(logfilepath).shuffle(buffer_size=1000) #.map(map_function)

dataset = dataset.map(
    lambda filename: tuple(tf.py_func(
        process_function, [filename],  [tf.double,tf.int64])))

dataset=dataset.batch(3)


In [51]:
iterator = dataset.make_initializable_iterator()
next_element = iterator.get_next()

In [52]:
with tf.Session() as sess:
    sess.run(iterator.initializer)
    for i in range(10):
      value = sess.run(next_element)
      print(value)

21_15_40090B.wav
21_15_40254B.wav
21_15_40263B.wav
(array([[[  1.56225025e-02,   2.03630193e-05,   9.40150085e-02, ...,
          -1.46918809e-02,  -1.71278307e-02,   7.10057669e-04],
        [  2.35407128e-02,   1.05381205e-05,   9.98923731e-02, ...,
          -5.21592913e-03,  -9.39042182e-03,   2.76683658e-05],
        [  1.95936669e-02,   5.11676610e-05,   7.10255012e-02, ...,
          -4.39842943e-03,  -5.71876141e-03,   6.13886896e-04],
        ..., 
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
           0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
           0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
           0.00000000e+00,   0.00000000e+00,   0.00000000e+00]],

       [[  1.28137505e-02,   1.43878991e-06,   7.08065099e-02, ...,
           3.41772290e-03,   1.43359163e-03,   9.29126648e-05],
        

(array([[[ 0.00563637,  0.00077179,  0.1279959 , ...,  0.00191654,
          0.00041429,  0.00078627],
        [ 0.00556476,  0.00129844,  0.13979672, ...,  0.00038603,
          0.00015412,  0.00139397],
        [ 0.00502366,  0.00106591,  0.13410206, ...,  0.01314108,
          0.00293131,  0.00084034],
        ..., 
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ]],

       [[ 0.00565638,  0.00077541,  0.14008396, ..., -0.03798282,
         -0.02769338,  0.00077838],
        [ 0.00802673,  0.0006196 ,  0.13893703, ..., -0.03482991,
         -0.02714522,  0.00090349],
        [ 0.01113843,  0.00059422,  0.1366344 , ..., -0.03060015,
         -0.01912645,  0.00040618],
        ..., 
        [ 0.        ,  0.        ,  0.        , ...

(array([[[ 0.00316726,  0.00047361,  0.13185312, ..., -0.00987825,
         -0.01717856,  0.0011717 ],
        [ 0.00283496,  0.00055294,  0.1314125 , ..., -0.02752312,
         -0.01823668,  0.00097626],
        [ 0.00244409,  0.00063147,  0.12992652, ..., -0.03179629,
         -0.00412991,  0.00066408],
        ..., 
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ]],

       [[ 0.00392942,  0.0035696 ,  0.14182653, ...,  0.00254153,
          0.00405815,  0.00133683],
        [ 0.00433025,  0.00249512,  0.14266951, ..., -0.00149054,
          0.00965014,  0.00206395],
        [ 0.00441654,  0.00245421,  0.14340235, ..., -0.00575008,
          0.00839639,  0.00175151],
        ..., 
        [ 0.        ,  0.        ,  0.        , ...

In [44]:
audio_to_features('/media/saurabh/New Volume/tf_audio_sentiment/data_test/datav2/21_27_17102A.wav').shape

(121, 22)